name: bank_lite
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  collapsible: ^1.0.0
  google_maps_flutter_web: ^0.3.2+1
  google_maps_flutter: ^2.1.3
  yandex_mapkit: ^2.0.2
  permission_handler: ^9.2.0
  fluttertoast: ^8.0.9
  universal_html: ^2.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.1.0
  provider: ^5.0.0
  flutter_local_notifications: ^9.4.0
  http: any
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_gen_runner: ^3.1.1
  percent_indicator: ^3.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/json/items.json
  fonts:
    - family: sfProDisplay
      fonts:
        - asset: lib/assets/fonts/SFProDisplay-Bold.otf
        - asset: lib/assets/fonts/SFProDisplay-Medium.otf
        - asset: lib/assets/fonts/SFProDisplay-Regular.otf
        - asset: lib/assets/fonts/SFProDisplay-Semibold.otf
    - family: sfProText
      fonts:
        - asset: lib/assets/fonts/SFProText-Medium.otf

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: false
  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter
